### ISSUE TITLE
Merged texture has artifacts

### ISSUE THREAD

**Issue by jb4twin** [Fidifis/TextureMerge#10] opened 2023-10-31 05:14 UTC
Hi, I don't know why.

![image](https://github.com/Fidifis/TextureMerge/assets/125167123/92d266c0-197e-456f-8e68-efe9c761f30c)

![ground-tiles-merged3](https://github.com/Fidifis/TextureMerge/assets/125167123/33a72706-b090-41ca-bde5-a4756260c3cf)

**Comment by Fidifis** [comment] 2023-10-31 15:17
Hi, yes that's strange. can you please send me the files that don't work so I can see in detail where the problem is?
Or any procedure on how to replicate the error.

**Comment by jb4twin** [comment] 2023-11-02 10:59
Sure, I got them fron here -> https://freestylized.com/material/ground_tiles_01/

**Comment by Fidifis** [comment] 2023-11-02 17:12
Resolved in [v1.4.1](https://github.com/Fidifis/TextureMerge/releases/tag/v1.4.1)
If you are still having trouble please reopen the issue.

**Closed by Fidifis** 2023-11-02 17:12 UTC
Labels: bug
